### ISSUE TITLE
Show method names and arg types in methods section

### ISSUE THREAD

**Issue by keerath** [Imaginea/KodeBeagle-UI#7]
Currently, when java.io.FileInputStream is search "read" under the methods shows up 3 times due to overloading. So it would be appropriate to show the arg types also.

**Comment by sudarshanch** [comment]
@keerath does this needs any UI change or its API change?

**Comment by keerath** [comment]
@sudarshanch this does not require any change in the UI. Have appended arg types to method names. So closing this issue.
